### ISSUE TITLE
:question: `manuscript_config.ini` port mapping conflicts

### ISSUE THREAD

**Issue by KagemniKarimu** [chainbase-labs/manuscript-core#101]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/chainbase-labs/manuscript-core/discussions).
- [X] I have searched for existing issues [search for existing issues](https://github.com/chainbase-labs/manuscript-core/issues), including closed ones.
- [X] I have searched for existing pull requests [search for existing pull requests](https://github.com/chainbase-labs/manuscript-core/pulls), including closed ones.

### Environment

```
📜 Manuscript Core:
  Version:	1.1.0

🏗️  Build Information:
  Go Version:	go1.22.5
  Rust Version:	1.83.0
  Git Commit:	a785c3c
  Built:	2024-12-13:16:28:46

💻 System Information:
  Unix Name:	Linux fedora-workstation 6.11.11-300.fc41.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Dec  5 18:38:25 UTC 2024 x86_64 GNU/Linux
  OS/Arch:	linux/amd64

🐳 Docker Environment:
  Docker:	'27.4.0'
```

### Steps to reproduce

1. Create a manuscript with cli `init` command
2. The ports are mapped using the `InitializePorts()` func
3. Stop the manuscript and restart it using the `depoy` command
4. Run `init` on a new manuscript
5. Do this combination a couple different times a couple different ways. 
Watch pandemonium ensue!

### ✔️ Expected Behavior

All logic for port /manuscript management needs to live in one place and one place only. Because aspects of the manuscripts are defined in their YAML, I would recommend that port management be removed from the `manuscript_config.ini`  until a more elegant solution is found.

_ONE SOLUTION_ :star: 
Implement user-controls for config management:

-  a `config` command that allows a user to DISPLAY and CHANGE aspects of their config file. Also, tells a user its path on disk.
- a global `config` flag that allows most commands to run from the specified config file instead of one in the default location
- a `clean` command or flag that allows a user to WHOLLY wipe out their config file, or WIPE all manuscripts
- a `start` command where a user can deploy any manuscript from a config without listing the entire path or parameters for the manuscript in question (this would speed up deploys & make better use of the `manuscript_config.ini`)

```go
# just an example, implementation can vary :)
var cleanCmd = &cobra.Command{
    Use:   "clean [manuscript-name]",
    Short: "Clean up manuscript configurations",
    Long: `Clean up manuscript configurations and optionally remove from disk.
    
Without arguments: List manuscripts that can be cleaned
--manuscript: Clean specific manuscript from config
--full: Completely delete the config file
--sweep: Clean all manuscripts from config
--deep: Also remove manuscript files from disk`,
    Run: func(cmd *cobra.Command, args []string) {
        manuscript, _ := cmd.Flags().GetString("manuscript")
        all, _ := cmd.Flags().GetBool("all")
        deep, _ := cmd.Flags().GetBool("deep")
        
        if manuscript != "" {
            cleanManuscript(manuscript, deep)
        } else if all {
            cleanAllManuscripts(deep)
        } else {
            listCleanableManuscripts()
        }
    },
}
```

### ❌ Actual Behavior

This issue is related to #62 , and tangentially #61 .
Each `manuscript.yaml` contains some information about the mapping of ports. For example,
```yaml
sinks:
  - name: ethereum_blocks_sink
    type: postgres
    from: ethereum_blocks_transform
    database: ethereum
    schema: public
    table: blocks
    primary_key: block_number
    config:
      host: postgres
      port: 5432  # <---  HERE!
      username: postgres
      password: postgres
```

Yet `manuscript_config.ini` also contains pertinent information about port mappings and existing manuscripts.

**Comment by Liquidwe** [comment]
This issue indeed has not been considered, we can solve this problem by partitioning the container network name. fixed #104
