### ISSUE TITLE
:1234: Create `--verbose` or `--debug` flag for version command

### ISSUE THREAD

**Issue by KagemniKarimu** [chainbase-labs/manuscript-core#70]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/chainbase-labs/manuscript-core/issues), including closed ones.
- [X] I have searched for existing pull requests [search for existing pull requests](https://github.com/chainbase-labs/manuscript-core/pulls), including closed ones.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

When creating new issues, users currently have to manually grab information for the following:
- `manuscript-core`
- `docker`
- `docker desktop`
- `system info`

Instead, let's create a flag `--verbose` (`-v`) or `--debug` (`-d`) which outputs all of the following information:
```bash
$ manuscript-cli version
manuscript-cli version 1.0.4

$ manuscript-cli version --verbose
Manuscript CLI:
  Version:    1.0.4
  Go version: go1.21.0
  OS/Arch:    darwin/arm64

System Information:
  Darwin MacBook-Pro.local 23.0.0 Darwin Kernel Version 23.0.0: x86_64

Docker Environment:
  Docker Engine:   '24.0.6'
  Docker Desktop:  '24.0.6'
```

### 2. Could you assist us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by KagemniKarimu** [comment]
Answered in #76 
Once merged, we can update our issues template to tell users of the cli to run `./manuscript-cli version -v` and copy and paste the data into the issue from the terminal.

**Comment by KagemniKarimu** [comment]
PR #76 has been merged! :recycle: 

We can now update the issues template. 

(I don't have access to do so @lxcong )

**Comment by Liquidwe** [comment]
Tks @KagemniKarimu, The latest branch has been merged into the main trunk, I have closed this issue.
