### ISSUE TITLE
CI/CD codespell check always fails with false positives

### ISSUE THREAD

**Issue by KagemniKarimu** [chainbase-labs/manuscript-core#71]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/chainbase-labs/manuscript-core/discussions).
- [X] I have searched for existing issues [search for existing issues](https://github.com/chainbase-labs/manuscript-core/issues), including closed ones.
- [X] I have searched for existing pull requests [search for existing pull requests](https://github.com/chainbase-labs/manuscript-core/pulls), including closed ones.

### Environment

N/A - github related

### Steps to reproduce

1. Initiate a PR :recycle: 
2. Look at checks :ballot_box_with_check: 

## Prospective Issue
- `crate` for rust packages is being mistaken for a typo for `create`
- codespell also thinks `ratatui` is misspelled

### ✔️ Expected Behavior

![image](https://github.com/user-attachments/assets/48ede2e9-6f8a-4028-94fa-3e1229c7416f)
![image](https://github.com/user-attachments/assets/caef0a03-cca0-4b61-a9d8-a7d71a54b6db)

### ❌ Actual Behavior

![image](https://github.com/user-attachments/assets/37a2ccf6-7516-4297-a908-c312d46a24ca)
![image](https://github.com/user-attachments/assets/3d020914-0f70-4acf-9ae9-0bf28986b34b)

**Comment by Liquidwe** [comment]
Our test project will mainly shift to Rust and Java in the follow-up, and this test task will be cancelled first.
