### ISSUE TITLE
Parsing Error causes manuscript-gui to not load

### ISSUE THREAD

**Issue by KagemniKarimu** [chainbase-labs/manuscript-core#72]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/chainbase-labs/manuscript-core/discussions).
- [X] I have searched for existing issues [search for existing issues](https://github.com/chainbase-labs/manuscript-core/issues), including closed ones.
- [X] I have searched for existing pull requests [search for existing pull requests](https://github.com/chainbase-labs/manuscript-core/pulls), including closed ones.

### Environment

> **Linux**: Linux fedora-workstation 6.11.10-300.fc41.x86_64 #1 SMP PREEMPT_DYNAMIC Sat Nov 23 00:51:20 UTC 2024 x86_64 GNU/Linux
> **Docker**: Docker version 27.3.1, build ce12230 , Docker Desktop 4.36.0 (175267)
> **Manuscript-core:** Latest commit (as of 12/06/2024)

### Steps to reproduce

1. Run the following command
```bash
curl -fsSL  https://github.com/chainbase-labs/manuscript-core/raw/main/install-gui.sh | bash
```
2. Execute the binary:
```
./manuscript
```

### ✔️ Expected Behavior

![image](https://github.com/user-attachments/assets/ec490879-8e87-44b7-87ee-38caefd23590)

### ❌ Actual Behavior

Failed to parse JSON response: reqwest::E┃ror { kind: Decode, source: Error("missing field `transactionLogs`", line: 1, column: 10452) }

https://github.com/user-attachments/assets/fa5b0121-d0ec-4e46-96d1-9427cedeaebd

**Comment by Liquidwe** [comment]
an update was released, can you check if there are still any issues?

**Comment by KagemniKarimu** [comment]
@Liquidwe The update fixed my issue! Thank you :100:
