### ISSUE TITLE
Kafka create sink statement had issue

### ISSUE THREAD

**Issue by junyoungcross** [chainbase-labs/manuscript-core#86]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/chainbase-labs/manuscript-core/discussions).
- [X] I have searched for existing issues [search for existing issues](https://github.com/chainbase-labs/manuscript-core/issues), including closed ones.
- [X] I have searched for existing pull requests [search for existing pull requests](https://github.com/chainbase-labs/manuscript-core/pulls), including closed ones.

### Environment

-

### Steps to reproduce

-

### ✔️ Expected Behavior

The Kafka sink SQL statement should be correctly formed, with all placeholders replaced with the appropriate values. The topic should be used instead of the incorrect topoc keyword, and the SQL statement should execute successfully without errors.

### ❌ Actual Behavior

The Kafka sink SQL statement contains a typo with the word topoc instead of topic. This causes the SQL statement to be incorrectly formed, leading to errors during execution.

**Comment by KagemniKarimu** [comment]
Just a message to say - you're creation of this issue and subsequent PR was seen and appreciated! :heart: :100:  Thank you @junyoungcross
