### ISSUE TITLE
📁 Improve Repo Organization: separate `cli` and `gui`

### ISSUE THREAD

**Issue by KagemniKarimu** [chainbase-labs/manuscript-core#98]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/chainbase-labs/manuscript-core/issues), including closed ones.
- [X] I have searched for existing pull requests [search for existing pull requests](https://github.com/chainbase-labs/manuscript-core/pulls), including closed ones.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Rework the directory for better separation of concerns and clarity. Right now, the top-level directory contains a mixture of files shared by both `manuscript-cli` and ones special to `manuscript-gui` in the folder `gui.`. IT looks roughly like the following:

```
.
├── client
├── CODE_OF_CONDUCT.md
├── commands
├── examples
├── flink
├── go.mod
├── go.sum
├── gui
├── images
├── install-gui.sh
├── install.sh
├── LICENSE
├── main.go
├── Makefile
├── manuscript-cli
├── pkg
├── README.md
└── static
```

My proposal is to reorganize it so that shared resources remain in the top-directory, but the `cli` receives its own directory, as roughly shown below:
```
.
├── cli
├── gui
├── examples
├── flink                                # not sure if this one is used by both rpojects
├── images
├── install-gui.sh
├── install.sh
├── Makefile
├── LICENSE
├── CODE_OF_CONDUCT.md
└── README.md
```
This requires some tedious re-working of the go project and also the `Makefile` to ensure that paths are not broken - but it is not a super heavy lift. `manuscript-gui` is basically already encapsulated and won't need much changes.

For further context see #78 

### 2. Could you assist us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by Liquidwe** [comment]
🔥 I thought it would be cool

**Comment by Liquidwe** [comment]
Hi @KagemniKarimu , I've reorganized the catalog according to your comments #103
